- name: Get EC2 facts
  ec2_remote_facts:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:env": "{{ env }}"
  register: ec2_facts

- name: terminate already running EC2 instances with env tag if present
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ ec2_region }}"
    instance_id: "{{item.id}}"
    state: absent
  with_items: "{{ ec2_facts.instances}}"

- name: Create security group to open 22 and webdav port for income connections
  ec2_group:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    name: "{{ dns_name }}_security_group"
    description: "{{ dns_name }} security group"
    region: "{{ ec2_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: "{{ webdav_port }}"
        to_port: "{{ webdav_port }}"
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: firewall

- name: Delete an EC2 key if exists
  ec2_key:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    name: "{{ dns_name }}"
    region: "{{ ec2_region }}"
    state: absent

- name: Create and save private key using aws cli
  shell: "aws ec2 create-key-pair --key-name {{dns_name}} --query 'KeyMaterial' --output text > {{dns_name}}.pem"
  register: keypair

- name: chmod key
  shell: "chmod 400 {{dns_name}}.pem"

- name: Create an EC2 instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ dns_name }}"
    region: "{{ ec2_region }}"
    group_id: "{{ firewall.group_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    wait: yes
    instance_tags:
      env: "{{ env }}"
    count_tag: env
    exact_count: 1
  register: ec2


- name: Get EC2 facts
  ec2_remote_facts:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:env": "{{ env }}"
  register: ec2_facts

- name: Assign elastic ip to instance that we created
  ec2_eip:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ ec2_region }}"
    device_id: "{{ item.id }}"
    ip: "{{ elastic_ip }}"
  with_items: "{{ec2_facts.instances}}"


- name: Wait for SSH to come up
  wait_for:
    host: "{{ elastic_ip }}"
    port: 22
    delay: 15
    timeout: 320
    state: started
  with_items: "{{ ec2_facts.instances }}"


- name: Add DNS name to the webdav_project group
  when: ec2_facts|success
  add_host: hostname="{{ dns_name }}" groups=webdav_project
  with_items: "{{ ec2_facts.instances }}"